-- Creates the payment_report_parts table with all fields from the test data
CREATE TABLE payment_report_parts (
    id INT PRIMARY KEY,
    report_id INT,
    merchant_processor_account_id INT,
    merchant_outlet_id INT,
    rr_start_of_day_count INT,
    rr_start_of_day_volume INT,
    safeguard_start_of_day_count INT,
    safeguard_start_of_day_volume INT,
    new_funds_count INT,
    new_funds_volume INT,
    refund_count INT,
    refund_volume INT,
    sale_fee_count INT,
    sale_fee_volume INT,
    refund_fee_count INT,
    refund_fee_volume INT,
    created_at DATETIME,
    updated_at DATETIME NULL,
    sale_scheme_fee_volume INT,
    refund_scheme_fee_volume INT,
    sale_interchange_fee_volume INT,
    refund_interchange_fee_volume INT,
    sale_reseller_fee_volume INT,
    refund_reseller_fee_volume INT,
    sale_referrer_fee_volume INT,
    refund_referrer_fee_volume INT,
    sale_total_processing_fee_volume INT,
    refund_total_processing_fee_volume INT,
    chargeback_scheme_fee_volume INT,
    chargeback_reseller_fee_volume INT,
    chargeback_referrer_fee_volume INT,
    chargeback_total_fee_volume INT,
    dispute_refund_count INT,
    dispute_refund_volume INT,
    negative_dispute_volume INT,
    negative_dispute_count INT,
    positive_dispute_volume INT,
    positive_dispute_count INT
);

