-- Creates the payment_reports table with all fields from the test data
CREATE TABLE payment_reports (
    id INT PRIMARY KEY,
    merchant_id INT,
    one_off_fee_count INT,
    one_off_fee_volume INT,
    settlement_fee_count INT,
    settlement_fee_volume INT,
    settled_volume INT,
    created_at DATETIME,
    updated_at DATETIME NULL,
    report_date DATE,
    rr_start_of_day_volume INT,
    safeguard_start_of_day_volume INT,
    report_update_date_time DATETIME NULL,
    dispute_reserve_volume INT,
    account_transfer_credit_volume INT,
    account_transfer_credit_count INT,
    account_transfer_debit_volume INT,
    account_transfer_debit_count INT,
    report_date_time_from DATETIME,
    report_date_time_until DATETIME,
    immature_sales_volume INT,
    mature_sales_volume INT,
    calculated_for_settlement_volume INT,
    rr_expired_volume INT,
    debt_to_operator_volume INT,
    debt_to_operator_diff_volume INT
);

