version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_test_db
    environment:
      POSTGRES_DB: postgres_test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - ./dump-postgres-202508231122.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: unless-stopped
