version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: dvdrental
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dvdrental.tar:/tmp/dvdrental.tar
    restart: unless-stopped
